apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ratings-web-agic-ingress
  namespace: ratingsapp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: ratings-web
                port:
                  number: 80
            pathType: Prefix
            path: /
          - backend:
              service:
                name: aksdemo
                port:
                  number: 80
            pathType: Prefix
            path: /test
